### ISSUE TITLE
client_secret for webapp_oidc as not required

### ISSUE THREAD

**Issue by coolsylver** [marcozj/terraform-provider-centrify#3]
**Description**: 
Can the **client_secret** field for webapp_oidc not be forced to be required? From my understand and testing, this field is not required when creating the application. However it is required for the application to be in ready state.

**Use case:** 
We are using this provider for keeping the centrify configuration infrastructure as a code, and this it publicly viewable by the  company wide. This field client_secret is somewhat sensitive and we don't want to expose it in the code. There would be different way to mange this field (ie manual, hashicorp vault or others) once the app is created.

**Comment by coolsylver** [comment]
Fix, see https://github.com/marcozj/terraform-provider-centrify/pull/4

**Comment by coolsylver** [comment]
Thanks for merging the PR. After testing, I found the PR worked but unfortunately the result is not as intended. 

Making it optional just default the value to empty string. One solution is to remove client_secret field from the schema, essentially making it a unmanaged field. However, this approach *might* cause issue to other use-case where one would want to manage this field in the code, but managing this field is bad security practice and should not be encouraged.

Thoughts @marcozj ?

**Comment by marcozj** [comment]
client_secret is a mandatory field in UI in fact. If you don't want Terraform to manage it, perhaps you can set a dummy value and change it later via other means.

**Comment by coolsylver** [comment]
I have tried with the dummy value, however on the next terraform run, it just override the value.

**Comment by marcozj** [comment]
You can try this

lifecycle {
      ignore_changes = [
        client_secret,
        ]
    }

**Comment by coolsylver** [comment]
Thanks for sharing that, I'll try it out.
